spring:
  application:
    name: service-discovery

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"