spring:
  application:
    name: filling-service

  datasource:
    url: jdbc:mysql://fillingdb-cluster.db.svc.cluster.local:3306/finpagodb?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false

