spring:
  application:
    name: filling-service

  datasource:
    write:
      jdbc-url: jdbc:mysql://fillingdb-router.db.svc.cluster.local:6446/finpagodb?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      jdbc-url: jdbc:mysql://fillingdb-router.db.svc.cluster.local:6447/finpagodb?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

common:
  redis:
    enabled: false
  kafka:
    enabled: false
  discovery:
    enabled: false


eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

  cloud:
    discovery:
      enabled: false
