spring:
  application:
    name: filling-service

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


