server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/api/users/**
            - Path=/v1/api/auth/**
            - Path=/v1/api/stocks/**
            - Path=/v1/api/likes/**
          filters:
            - PreserveHostHeader

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/api/order/**
        - id: execution-service
          uri: lb://execution-service
          predicates:
            - Path=/v1/api/execution/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/api/notification/**
        - id: filling-service
          uri: lb://filling-service
          predicates:
            - Path=/v1/api/filling/**
            - Path=/v1/api/news/**

      discovery:
        locator:
          enabled: true

jwt:
  secret: "greenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonT"
  expiration: 86400000
