stocks = [
    { "ticker": "AAPL", "name": "애플" },
    { "ticker": "MSFT", "name": "마이크로소프트" },
    { "ticker": "NVDA", "name": "엔비디아" },
    { "ticker": "AMZN", "name": "아마존닷컴" },
    { "ticker": "GOOG", "name": "알파벳 C주" },
    { "ticker": "META", "name": "메타 플랫폼스(페이스북)" },
    { "ticker": "AVGO", "name": "브로드컴" },
    { "ticker": "TSLA", "name": "테슬라" },
    { "ticker": "COST", "name": "코스트코 홀세일" },
    { "ticker": "NFLX", "name": "넷플릭스" },
    { "ticker": "TMUS", "name": "T-모바일 US" },
    { "ticker": "ASML", "name": "ASML 홀딩 ADR" },
    { "ticker": "CSCO", "name": "시스코 시스템즈" },
    { "ticker": "PEP", "name": "펩시코" },
    { "ticker": "ADBE", "name": "어도비" },
    { "ticker": "PLTR", "name": "팔란티어 테크놀로지스 A주" },
    { "ticker": "PDD", "name": "핀둬둬 ADR" },
    { "ticker": "AMD", "name": "AMD" },
    { "ticker": "QCOM", "name": "퀄컴" }
]