stocks = [
    {"ticker": "AAPL", "name": "애플"},
    # {"ticker": "MSFT", "name": "마이크로소프트"},
    # {"ticker": "NVDA", "name": "엔비디아"},
    # {"ticker": "GOOGL", "name": "알파벳"},
    # {"ticker": "AMZN", "name": "아마존"},
    # {"ticker": "META", "name": "메타"},
    # {"ticker": "TSLA", "name": "테슬라"},
    # {"ticker": "LLY", "name": "일라이 릴리"},
    # {"ticker": "AVGO", "name": "브로드컴"},
    # {"ticker": "JPM", "name": "JP모건"},
    # {"ticker": "IBM", "name": "IBM"},
    # {"ticker": "MA", "name": "마스터카드"},
    # {"ticker": "ORCL", "name": "오라클"},
    # {"ticker": "COST", "name": "코스트코"},
    # {"ticker": "UNH", "name": "유나이티드헬스"},
    # {"ticker": "NFLX", "name": "넷플릭스"},
    # {"ticker": "AMD", "name": "AMD"},
    # {"ticker": "TSM", "name": "TSMC"},
    # {"ticker": "ADBE", "name": "어도비"},
    # {"ticker": "CRM", "name": "세일즈포스"},
    # {"ticker": "NOW", "name": "서비스나우"},
    # {"ticker": "INTC", "name": "인텔"},
    # {"ticker": "PLTR", "name": "팔란티어"},
    # {"ticker": "ASML", "name": "ASML"},
    # {"ticker": "V", "name": "비자"},
    # {"ticker": "XOM", "name": "엑슨모빌"},
    # {"ticker": "KO", "name": "코카콜라"},
    # {"ticker": "WMT", "name": "월마트"},
    # {"ticker": "LIN", "name": "린데"},
    # {"ticker": "MS", "name": "모건스탠리"},
]