spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://userdb-cluster.db.svc.cluster.local:3306/finpagodb?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
    open-in-view: false
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
common:
  redis:
    enabled: true
  kafka:
    enabled: true
  discovery:
    enabled: false

jwt:
  secret: "greenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonT"
  expiration: 86400000

feign:
  client:
    config:
      order-service:
        url: http://order-service.default.svc.cluster.local

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

  cloud:
    discovery:
      enabled: false