spring:
  application:
    name: common


common:
  redis:
    enabled: true
    password: CTg0n49k0M
    client-type: lettuce
    read-from: replica
    cluster:
      nodes:
        - 192.168.3.156:6379  # Master 1
        - 192.168.51.134:6379 # Master 2
        - 192.168.52.187:6379 # Master 3
      max-redirects: 3
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 60s

